
Init:
    timeout: -1
    condition: { true }


DisableOnStart:  # отключает управление игроков на старте
    disablePlayers: true
    time: 5  # секунд
    onDisableText: |
        <t color='#AAAAAA' font='PuristaLight' size='0.8'>
        Управление отключено, не паникуй!<br /><br />
        - Не нажимай кнопок<br />
        - Прослушай ORBAT<br />
        - Запомни своего командира и напарника</t>
    onEnableText: |
        <t color='#FFE240' font='PuristaLight'>Удачной Игры!</t>
    showOrbat: true
    orbatPrefixSortingOrder:  # порядок сортировки по префиксам
        - RED
        - BLUE

Equipment:
    EarplugAutoUse: true  # автоматически втыркает беруши
    PutWeaponOnSafe: true  # ставит оружие на предохранитель

PlayerRating:  # больший рейтинг позволяет совершать больше убийств союзников без последствий
    enable: true
    rating: 25

Calculator:
    enable: true

PhoneticAlphabet:  # автозаполняет имя маркера, если в его имени есть (литера)+(восклицательный знак)
    enable: true
    BLUFOR:
        - Alpha
        - Bravo
        - Charlie
        - Delta
        - Echo
        - Foxtrot
        - Golf
        - Hotel
        - India
        - Juliett
        - Kilo
        - Lima
        - Mike
        - November
        - Oscar
        - Papa
        - Quebec
        - Romeo
        - Sierra
        - Tango
        - Uniform
        - Victor
        - Whiskey
        - X-ray
        - Yankee
        - Zulu
    OPFOR:
        - Анна
        - Борис
        - Василий
        - Григорий
        - Дмитрий
        - Елена
        - Женя
        - Зоя
        - Иван
        - Константин
        - Леонид
        - Михаил
        - Николай
        - Ольга
        - Павел
        - Роман
        - Семен
        - Татьяна
        - Ульяна
        - Федор
        - Харитон
        - Цапля
        - Чайка
        - Шура
        - Щука
        - Эхо
        - Юрий
        - Яков
    GUER: *PhoneticAlphabet > BLUFOR
