# Crew Options
# ---
#
#
# Зависимости:
#   dzn_gear/dzn_dynai

# Выбирет машину, затем откройте tSF 3DEN Tool > [Vehicle] Add crew options
#  или
# Засинхронизируйте машины/статичные орудия в редакторе с GameLogic с инит-кодом:
#   this setVariable ["tSF_CrewOptions", "Config name"]
# Для всех засинхронизированных машин будет добавлено действие для создания экипажа, с настройками согласно
# выбранному конфигу.

Init:
    timeout: 3
    condition: { true }

# -- Значения по умолчанию:
#    kit         - string, dzn_gear кит для бота, по умолчанию - без кита
#    class       - string, класс бота, по умолчанию выбирается ванильный класс экипажа в зависимости от стороны игрока
#    allowCombat - bool, должен ли бот участвовать в бою, по умолчанию false - бот будет игноировать цели, если ему их не назначит игрок
Defaults:
    kit: ""

# -- "Слоты" можно описать отдельно, а затем переиспользовать в разных конфигах. 
#    Не указанные значения будут наследоваться из соответсвующего конфига.
SeatDriver:
    seat: driver 
    name: Водитель


# -- Описание конфигов
Configs:
    # -- Имя конфига (для указания в переменной tSF_CrewOptions связанного GameLogic)
    Driver:   
        # -- Опционально, Список подстрок для проверки роли игрока: 
        #    только игроки с соответствующими ролями могут добавлять AI-экипаж
        #    Например, игрок с ролью "1`5 Экипаж" будет иметь доступ. 
        #    По умолчанию равен [""] - т.е. будет доступно всем ролям.
        allowedForRoles: ["Экипаж", "Crew"]
        
        # -- Опционально, Общие настройки AI-экипажа, если не указаны, то используются значения из Defaults
        # class: "B_rifleman_F"  
        # kit: ""
        
        # -- Настройки слотов для AI-экипажа
        crew:
            - seat: driver        # имя слота/места: driver, gunner, commander или в формате [0], [0,1] (см. https://community.bistudio.com/wiki/allTurrets)
              name: Водитель      # имя для меню
              # class: "B_crew_F"   # опционально, класс юнита (если не задан, то кит конфига)
              # kit: ""             # опционально, кит (если не задан, то кит конфига, если "" - не применяет кит)
              # allowCombat: false  # отключает боту возможность автоматически выбирать цель и атаковать


    # -- Пример с переиспользованием слота определенного в корне документа
    # CrewDriver:
    #     allowedForRoles: ["Экипаж", "Crew"]
    #     class: "B_crew_F"
    #     crew:
    #         - *SeatDriver   # Можно использовать ссылку

    #HelicopterFull:
    #    allowedForRoles: ["Pilot", "Пилот"]
    #    kit: ""
    #    class: "B_Helipilot_F"
    #    crew:
    #        - name: Пилот
    #          seat: driver

    #        - name: Второй пилот
    #          seat: [0]

    #        - name: Бортстрелок (левый)
    #          seat: [1]                     # путь турели
    #          class: "B_helicrew_F"
    #          kit: "kit_west_doorgunner"
    #          allowCombat: true

    #        - name: Бортстрелок (правый)
    #          seat: [2]
    #          class: "B_helicrew_F"
    #          kit: "kit_west_doorgunner"
    #          allowCombat: true

