# Crew Options
# ---
#
#
# Зависимости:
#   dzn_gear/dzn_dynai

# Выбирет машину, затем откройте tSF 3DEN Tool > [Vehicle] Add crew options
#  или
# Засинхронизируйте машины/статичные орудия в редакторе с GameLogic с инит-кодом:
#   this setVariable ["tSF_CrewOptions", "Config name"]
# Для всех засинхронизированных машин будет добавлено действие для создания экипажа, с настройками согласно
# выбранному конфигу.

# [ Управление экипажем                Х ]
# [ Водитель                      [  +  ]]
# [ *Стрелок                      [  -  ]]
#
#
#
#
#



Init:
    timeout: 3
    condition: { true }


Defaults:
    side: west
    unit: "B_crew_F"
    kit: ""


Configs:
    Driver:
        count: 1
        crew:
            - seat: driver

    CrewDriver:
        count: 1
        crew:
            - seat: driver

    Helicopter Pilot:
        count: 2
        kit: "kit_west_pilot"
        crew:
            - seat: driver

    Helicopter Doorgunner:
        count: 2
        kit: "kit_west_doorgunner"
        crew:
            - seat: [0]
            - seat: [1]

    Helicopter FFV:
        count: 2
        kit: "kit_west_mgunner_ffv"
        crew:
            - seat: ffv_1
            - seat: ffv_2
