# Editor Radio Settings
# ---
# Позволяет настроить радио на технике, явно задавая конкретный вид радиостанций.
# Например, оснастить танк армии РФ рацией BLUFOR.
#
# Зависимости:
# нет

# Выбирет машину, затем откройте tSF 3DEN Tool > [Vehicle] Add TFAR LR radio
#  или
# Засинхронизируйте машины в редакторе с GameLogic с инит-кодом:
#   this setVariable ["tSF_ERS_Config", "Config name"]
# Для всех засинхронизированных машин будет добавлена радиостанция из выбранной
# конфигурации


Init:
    timeout: 1
    condition: { true }

# Настройки на которые ссылаются стандартные конфигурации
Defaults:
    range: 30000    # дальность работы в метрах
    isolation: 0.5  # степень изолированности техники от звуков снаружи
                    # влияет на слышимость голосов снаружи-внутри
    overrideIsolation: false  # флаг, чтобы перезаписать степень изолированности
                              # если она задана в конфиге (иначе не перезаписываем)

Configs:
    # Пример:
    # MyCustomConfig:
    #     side: west              # сторона рации (чтобы иметь общие настройки частот и каналов с выбранной стороной)
    #     class: "tf_rt1523g"     # класс радиостанции
    #     range: 25000            # (опционально, см. выше)
    #     isolation: 0.5          # (опционально, см. выше)
    #     overrideIsolation: true # (опционально, см. выше)

    BLUFOR:
        side: west
        class: "tf_rt1523g"

    OPFOR:
        side: east
        class: "TFAR_mr3000"

    INDEP:
        side: resistance
        class: "TFAR_anprc155"
