# Authorization
# ---
# Определяет доступность разных модулей роли игрока


# -- Значения для ссылок - все роли названные на "_" или "#" будут проигнорированы
_All: [Artillery, Airborne, POM]
_Services: [Artillery, Airborne]

# -- Глобальная настройка - если что-то указано для этой роли, 
#    то все игроки получат доступ к указанным модулям
Everyone: []

# -- Роль (частичное совпадение) и ее авторизации (*_All - ссылка на )
Platoon Leader: *_All
Platoon Sergeant: *_All
Командир взвода: *_All
Зам. командира взвода: *_All

ПАН: *_All
JTAC: *_All
FO: [Artillery]
КАО: [Artillery]

Squad Leader: *_Services
Командир отделения: *_Services
