# Respawn
# ---
# Задает локации для респауна игроков, а также управление респауном со стороны GSO
#
# Зависимости: IntroText
#
# Ставим на карте объекты GameLogic с инит-кодом:
#   this setVariable ["tSF_RespawnLocation", "Default"]
# где Default - имя конфигурации респауна

Equipment:
    EarplugAutoUse: true   # автоматически втыкает беруши
    PutWeaponOnSafe: true  # ставит оружие на предохранитель


PlayerRating:  # небольшой рейтинг предотвращает проблемы с доступом к технике после случайного огня по своим
    enable: true
    rating: 200



# Локации и указания какие группы должны респаунится в этой локации.
# Локацию по умолчанию не указывается.
# Не указанные группы будут появлятся на локации по умолчанию.
Locations:
    Default:
        name: ""                    # Отображаемое имя
        description: "По умолчанию" # Описание (для GSO)
        # snapToSurface: true       # Нужно ли пытаться поставить игроков на ближайшую поверхость под ними
                                    # (например на палубу корабля под GameLogic). По умолчанию - да.
        # groups: []                # Список групп которые возрождаются на этой точке

    AircraftCarrier:
        name: "Авианосец"
        description: "Авианосец классу эсминец, для спецназа"
        groups:
            - Razor 1`1
            - Razor 1`2

    Convoy:
        name: "Конвой"
        description: "Позиция начала маршрута конвоя"
        groups:
            - Jupiter 1`1
            - Jupiter 1`2


# сообщение отображаемое перед респауном
BeforeRespawnMessage: "Подкрепления через %1 секунд..."
# сообщение отображаемое после респауна в hint parseText
OnRespawnMessage: |
    <t color="#334455" align="center" size="0.075">Вы в отряде %1</t><br>
    <t color="#334455" align="center">Ваши действия сейчас:</t><br>
    <t align="left">- Проверьте снаряжение</t><br>
    <t align="left">- Настройте рацию</t><br>
    <t align="left">- Ожидайте указаний от GSO</t>
