# Respawn
# ---
# Задает локации для респауна игроков, а также управление респауном со стороны GSO.
# Также выставляет оружие на предохранитель, вставляет затычки и выставляет рейтинг игрока
# как в начале миссии, так и после респауна.
#
# Зависимости: IntroText
#
# Ставим на карте объекты GameLogic с инит-кодом:
#   this setVariable ["tSF_RespawnLocation", "MyLocation"]
# где Default - имя конфигурации респауна

Equipment:
    EarplugAutoUse: true   # автоматически втыкает беруши
    PutWeaponOnSafe: true  # ставит оружие на предохранитель


PlayerRating:  # небольшой рейтинг предотвращает проблемы с доступом к технике после случайного огня по своим
    enable: true
    rating: 500


# -- Локации и указания какие группы должны респаунится в этой локации.
#    Не указанные группы будут появлятся на локации по умолчанию (маркер respawn / respawn_west / respawn_east).
Locations:
    Default:  # настройки для локации по умолчнию
        name: ""                    # Отображаемое имя (для IntroText - "" не будет отображаться)
        description: "Стандартный респаун" # Описание (для GSO)
        # snapToSurface: true       # Нужно ли пытаться поставить игроков на ближайшую поверхость под ними
                                    # (например на палубу корабля под GameLogic/маркером respawn). По умолчанию - true.

    IDAP Base:
        name: "Палатка IDAP"
        description: "Гурманитарная база IDAP"
        groups:                    # Список групп которые возрождаются на этой точке
            - Razor 1`1

    Highground:
        name: "Высотка"
        description: "Высокая позиция напротив базы IDAP"
        snapToSurface: true
        groups:
            - Razor 1`2



# -- Минимальная задержка перед респауном
BeforeRespawnTimeout: 5
# -- сообщение отображаемое перед респауном
BeforeRespawnMessage: "Подкрепления через %1 секунд..."
# -- сообщение отображаемое после респауна в hint parseText
OnRespawnMessage: |
    <t color="#AAAAAA"><t align="center" size="1.2">Вы в отряде %1</t><br/>
    Ваши действия сейчас:<br/>
    <br/>
    - Проверьте снаряжение<br/>
    - Настройте рацию<br/>
    - Ожидайте указаний от GSO</t>
# -- сообщение при отмене респауна
CancelRespawnMessage: "Подкрепления не будет."