# Respawn
# ---
# Задает локации для респауна игроков, а также управление респауном со стороны GSO
#
# Зависимости: IntroText
#
# Ставим на карте объекты GameLogic с инит-кодом:
#   this setVariable ["tSF_RespawnLocation", "MyLocation"]
# где Default - имя конфигурации респауна

Equipment:
    EarplugAutoUse: true   # автоматически втыкает беруши
    PutWeaponOnSafe: true  # ставит оружие на предохранитель


PlayerRating:  # небольшой рейтинг предотвращает проблемы с доступом к технике после случайного огня по своим
    enable: true
    rating: 500



# Локации и указания какие группы должны респаунится в этой локации.
# Локацию по умолчанию не указывается.
# Не указанные группы будут появлятся на локации по умолчанию (маркер respawn / respawn_west / respawn_east).
Locations:
    Default:  # настройки для локации по умолчнию
        name: ""                    # Отображаемое имя (для IntroText - "" не будет отображаться)
        description: "По умолчанию" # Описание (для GSO)
        # snapToSurface: true       # Нужно ли пытаться поставить игроков на ближайшую поверхость под ними
                                    # (например на палубу корабля под GameLogic/маркером respawn). По умолчанию - true.

    AircraftCarrier:
        name: "Авианосец"
        description: "Авианосец классу эсминец, для спецназа"
        snapToSurface: true
        groups:                    # Список групп которые возрождаются на этой точке
            - Razor 1`1
            - Razor 1`2

    Convoy:
        name: "Конвой"
        description: "Позиция начала маршрута конвоя"
        groups:
            - Jupiter 1`1
            - Jupiter 1`2


# Задержка перед респауном
BeforeRespawnTimeout: 5
# сообщение отображаемое перед респауном
BeforeRespawnMessage: "Подкрепления через %1 секунд..."
# сообщение отображаемое после респауна в hint parseText
OnRespawnMessage: |
    <t color="#AAAAAA"><t align="center" size="1.2">Вы в отряде %1</t><br/>
    Ваши действия сейчас:<br/>
    <br/>
    - Проверьте снаряжение<br/>
    - Настройте рацию<br/>
    - Ожидайте указаний от GSO</t>
