# Dependency: No

# Засинхронизируйте машины/статичные орудия в редакторе с GameLogic с инит-кодом:
#   this setVariable ["tSF_EVC", "Config name"]
# Для всех засинхронизированных машин будет создан экипаж, с настройками согласно
# выбранному конфигу.


Init:
    timeout: 1
    condition: { true }

# Настройки на которые ссылаются стандартные конфигурации вражеской стороны,
# вы можете изменить значения в соответствии с вашим сценарием
Defaults:
    side: east        # сторона экипажа: west, east, resistance, civilian
    vehicleKit: ""    # имя кита для машины (dzn_gear)
    crewClass: ""     # по умолчанию выбирает класс экипажа согласно стороне
                      # однако можно задать вручную.
                      # Следите за тем, чтобы класс относился к выбранной стороне!
    crewKit: ""       # имя кита для экипажа (dzn_gear)
    behavior: "full frontal"  # поведение маишны (dzn_dynai):
             # hold         - осматриваться на 360 градусов вокруг
             # frontal      - сектор 90 градусов (+-45 по направлению машины)
             # full frontal - сектор 180 градусов (+-90 по направлению машины)
    skill:             # навык экипажа (будет перезаписан, при выборе настроек)
        general: 0.75  # общий навык, если указан только он, то используется простая схема навыков
        # прочие навыки см. https://community.bistudio.com/wiki/setSkill -- будет использована расширенная схема (см. синтаксис 2)

Configs:
    # Пример:
    # MyCustomConfig:
    #     use: *Defaults  # набор значений по-умолчанию (если не указаны в конфиге, то будут взяты отсюда)
    #     # роли в машине: commander, gunner, driver
    #     roles:
    #         - gunner  # первый член команды станет лидером (поэтому должен сидеть на месте, где хоть что-то видно)
    #         - driver
    #     side: west
    #     crewClass: "B_Soldier_F"
    #     crewKit: "kit_blufor_light_crew"
    #     vehicleKit: "kit_cargo_opfor"
    #     skill:
    #         general: 0.75

    OPFOR VC, GNR, DRV:
        $use: *Defaults
        roles:
            - commander
            - driver
            - gunner

    OPFOR VC, DRV: ($use: *Defaults, roles: [commander, driver])
    OPFOR GNR, DRV: ($use: *Defaults, roles: [gunner, driver])
    OPFOR VC, GNR: ($use: *Defaults, roles: [commander, gunner])
    OPFOR VC: ($use: *Defaults, roles: [commander])
    OPFOR GNR: ($use: *Defaults, roles: [gunner])
    OPFOR DRV: ($use: *Defaults, roles: [driver])
