# JIP Teleport
# ---
# Позволяет JIP игрокам переместиться к своему отряду после подключения.
# Если игрок один в отряде - то только показываем сообщение MessageNoLeader.
#
# Зависимости: нет

Init:
    timeout: 1
    condition: { true }


# Время для того чтобы воспользоваться телепортом и дистанция от точки старта,
# выйдя за которую игрок теряет возможность телепорта
ExpirationTime: 10 * 60  # секунд (минимум 10),
ExpirationDistance: 75   # метров, дистанция


# Сообщение при входе в игру, где %1 - ExpirationTime, %2 - ExpirationDistance
Message: |
    У Вас есть %1 секунд, чтобы воспользоваться телепортом к вашему лидеру отделения.
    Также вы потеряете возможность телепорта, если отойдете на расстояние больше чем %2 метров от текущего места.

MessageNoLeader: |
    Вы единственный член группы. Ожидайте дальнейших инструкций от GSO.
    Вы можете связаться с GSO через клавишу F8.

MessageNoVehicleSeat: |
    Ваш лидер сейчас в машине в которой нет свободных мест.<br/>Попробуйте позже.
